#this simple program demonstrates the use of exception-handling in Python 

#Block to raise exception
try:
    #Raising the exception
    raise AttributeError

#Block to handle exception
except:
    print("Exception Handled")
